---
- name: Write a Ansible Playbook to create a group called deploy
  hosts: localhost
  tasks:
    - name: Create a group deploy
      group: name="deploy"
    - name: Create a user deploy_user
      user: 
        name: "deploy-user"
        group: "deploy"
        shell: "/bin/bash"
    - name: Install httpd
      yum: 
        name: "httpd"
        state: "installed"
    - name: Start httpd
      service: 
        name: "httpd"
        state: "started"
    - name: Create a index file
      file:
        path: "/var/www/html/index.html"
    - name: Reboot the machine
      reboot:
        reboot_timeout: 3600
    - name: Install git, wget
      yum:
        name: "git,wget"
    - name: Clone a repo
      git:
        repo: "https://github.com/scmgalaxy/ansible-role-template"
        dest: "/root/Ansible-Mexico-Az-June-2020/Ana D/repo"
...
