
- name: Clone Repo
  hosts: web
  tasks:
  - name: Clone git repo
    git: repo=https://github.com/scmgalaxy/ansible-role-template dest=/root/clonedrepo

- name: Copy index.html
  hosts: web
  tasks:
  - name: Copy index.html
    copy: src=index.html dest=/var/www/html

- name: Create group deploy
  hosts: web
  tasks:
  - name: Create group deploy
    group:  name=deploy

- name: Create user deploy-user
  hosts: web
  tasks:
  - name: Create user deploy
    user:  name=deploy-user groups=deploy

- name: Install git and wget
  hosts: web
  tasks:
  - name: Install git and wget
    yum: name=git,wget state=installed

- name: Install httpd
  hosts: web
  tasks:
  - name: Install httpd
    yum:  name=httpd state=installed

- name: Reboot machine
  hosts: web
  tasks:
  - name: Reboot machine
    reboot: reboot_timeout=10 msg="Rebooting host"

- name: Start httpd
  hosts: web
  tasks:
  - name: Start httpd
    service:  name=httpd state=started enabled=yes
