- name: Playbook of LabD1
  hosts: all
  tasks:
    - group: name=deploy state=present
    - user: name=deploy-user groups=deploy shell=/bin/bash
    - yum: name=httpd state=installed
    - service: name=httpd state=started enabled=true
    - copy:  dest=/var/www/html src="index.html"
    - yum: name=wget state=latest
    - yum: name=git state=latest
    - git: repo="https://github.com/scmgalaxy/ansible-role-template" dest=/src/ansible
    - file: path=/opt/devopsschool.txt state=touch
    - file: path=/opt/devopsschool.txt state=touch
    - file: path=/opt/devopsschool.txt state=absent
...
