- name: This is my frist playbook - Day2 Lab 2
  hosts: all
  tasks:

  - name: Create a user called deploy-user group deploy and shell /bin/bash
    user:
      name: deploy-user
      shell: /bin/bash
      group: deploy
